# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Diff drive controller --------------------------------------
diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: left_wheel_joint
  right_wheel: right_wheel_joint
  publish_rate: 100.0               # default: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Velocity and acceleration limits
  linear:
    x:
      has_velocity_limits: false
      has_acceleration_limits: false
      has_jerk_limits: false
      max_velocity: 3.0
      min_velocity: -3.0
      max_acceleration: 0.02
      min_acceleration: -0.02
      max_jerk: 1.0
      min_jerk: 1.0
  angular:
    z:
      has_velocity_limits: false
      has_acceleration_limits: false
      has_jerk_limits: false
      max_velocity: 3.0
      min_velocity: -3.0
      max_acceleration: 0.02
      min_acceleration: -0.02
      max_jerk: 1.0
      min_jerk: 1.0

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation: 0.22
  wheel_radius: 0.03
  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0  # default: 1.0
  wheel_radius_multiplier: 1.0  # default: 1.0
  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25
  # Base frame_id
  base_frame_id: base_link
  odom_frame_id: /odom
  # enable_odom_tf: false
