cube_petit/diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : "left_wheel_joint"
  right_wheel : "right_wheel_joint"

  publish_rate: 1000.0 #50
  cmd_vel_timeout: 30.0
  wheel_separation : 0.1403
  wheel_radius : 0.0325
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # tf
  enable_odom_tf: true
  base_frame_id: base_link
  odom_frame_id: odom

  # limits
  linear:
    x:
      has_velocity_limits    : false
      max_velocity           :  0.55 # m/s
      min_velocity           : -0.55 # m/s
      has_acceleration_limits: false
      max_acceleration       :  1.0 # m/s^2
      min_acceleration       : -1.0 # m/s^2
  angular:
    z:
      has_velocity_limits    : false
      max_velocity           :  1.5 # rad/s
      min_velocity           : -1.5 # rad/s
      has_acceleration_limits: false
      max_acceleration       :  1.0  # rad/s^2
      min_acceleration       : -1.0 # rad/s^2

cube_petit/gazebo_ros_control:
  pid_gains:
    right_wheel_joint:
      p: 0.1
      i: 0.0
      d: 0.0
      i_clamp_min: 0.0
      i_clamp_max: 0.0
      antiwindup: true
      publish_state: true
    left_wheel_joint:
      p: 0.1
      i: 0.0
      d: 0.0
      i_clamp_min: 0.0
      i_clamp_max: 0.0
      antiwindup: true
      publish_state: true

cube_petit/joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
