<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cube_petit_diagnostics</name>
  <version>0.0.0</version>
  <description>The cube_petit_diagnostics package</description>
  <maintainer email="SBGRP-git@g.softbank.co.jp">SoftBank corp.</maintainer>
  <license>Apache 2.0</license>
  <url type="repository">https://github.com/sbgisen/cube_petit_ros</url>
  <url type="bugtracker">https://github.com/sbgisen/cube_petit_ros/issues</url>
  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  <build_depend>python-is-python3</build_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>diagnostic_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>diagnostic_aggregator</exec_depend>
  <exec_depend>diagnostic_common_diagnostics</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
